platform :ios, '10.0'
require_relative '../node_modules/@unimodules/core/podfile-macro'

target 'sharePlaces' do
  # Pods for sharePlaces
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_unimodules!
  # Add pods for additional unimodules here

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-location', :path => '../node_modules/react-native-location'

  target 'sharePlacesTests' do
    inherit! :search_paths
  end
end